### PR TITLE
Included auto upload boolean property

### PR DESCRIPTION
**Pull request by LKozakewycz**
This property stops files from being automatically uploaded paving way for manual uploads.

### CODE REVIEW

**Comment by AustinGomez** [comment]
@seanadkinson any chance you'd be able to take a look at this?

**Comment by seanadkinson** [comment]
@LKozakewycz Looks great!  Sorry for the delay on this guys.

**Comment by seanadkinson** [comment]
Fixes #95

**Comment by seanadkinson** [comment]
Released with `v.4.6.0`

**Pull request merged**
