### PR TITLE
Add onSignedUrl() handler

### PR DESCRIPTION
**Pull request by charltoons**
I have a situation where I need to handle the data returned from the signingUrl server as soon as it's available. The simplest solution I could see was to expose an onSignedUrl handler that passes back that info before uploading. I tried to make it conform to the style of all the others, so it would be a simple addition to the lifecycle handlers.

### CODE REVIEW

**Comment by seanadkinson** [comment]
Looks good, thank you.

**Comment by seanadkinson** [comment]
Published `v4.7.0`

**Comment by iwarshak** [comment]
Does this callback allow you to manipulate the actual signed URL, or is it just a notification of what the signed url is?

**Comment by seanadkinson** [comment]
@iwarshak Not intentionally used for manipulation, but since the signing result is a javascript object, you could theoretically change it before it gets used.

**Pull request merged**
