### PR TITLE
Added flask section to readme

### PR DESCRIPTION
**Pull request by dan-compton**
I'm not sure if the differences between flask and Django are significant enough to mandate a new section to the readme.  However, I've included a rough draft of what that might look like below (apologize for the large diff).  Let me know what you think.

### CODE REVIEW

**Comment by seanadkinson** [comment]
Can you add node_modules to .gitignore, and delete node_modules and commit?  Too many files to go through here. Thanks.

**Comment by dan-compton** [comment]
Sure thing

**Comment by seanadkinson** [comment]
Looks like this PR still has all the node_modules in it.  Need to trim down this PR before I can merge.

**Comment by dan-compton** [comment]
I've been forgetting about this for too long.

**Pull request closed without merging**
